name = "playground"
targets = ["web"]
dependencies = ["std", "vdom"]
test-dependencies = []
ditto-version = ">=0.0.3"

[[package-set.extends]]
url = "https://raw.githubusercontent.com/ditto-lang/package-sets/63709a6d571b512bc3bce50c18d3683113a061f2/packages.toml"
sha256 = "9009d6a4d00224226455dec41a653bb2e04d67a341e41c2c43e2716f62243f43"

[package-set.packages.vdom]
path = "../vdom"

[package-set.packages.js-task]
path = "../js-task"
