# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
# https://rust-lang.github.io/rustup-components-history/
[toolchain]
channel = "nightly-2023-02-13"
profile = "minimal"
components = ["rustfmt", "clippy", "rust-src"]
targets = ["wasm32-unknown-unknown"]
